version: "3.9"
services:
  web:
    build: ./frontend
    ports: 
      - "3000:3000"
    volumes: 
      - ./frontend:/usr/src/app
    depends_on: 
      - server
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:80
  server:
    build: ./backend
    ports: 
    - "80:5000"
    volumes: 
    - ./backend:/app
    environment: 
      FLASK_ENV: development