version: "3.9"
services:
  web:
    container_name: frontend_container
    build: ./frontend
    ports: 
      - "3001:3001"
    volumes: 
      - ./frontend:/usr/src/app
    depends_on: 
      - server
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:80
    networks:
      - mynetwork
    
  server:
    container_name: backend_container
    build: ./backend
    ports: 
    - "80:5000"
    volumes: 
    - ./backend:/app
    environment: 
      FLASK_ENV: development
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge

